const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=pathToFileURL(path.resolve(__dirname,'../../docs/flow-comparison/index.html')).href;
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  const term=page.locator('#contracts .term-tooltip').first();
  await term.hover();
  const tip=page.locator('#term-explanation');
  await tip.waitFor({state:'visible',timeout:2000});
  assert.match(await tip.innerText(),/같은 DB 트랜잭션/);
  await tip.hover();assert(await tip.isVisible(),'tooltip must remain readable when hovered');
  await page.keyboard.press('Escape');assert(await tip.isHidden());
  await term.focus();await tip.waitFor({state:'visible'});
  await page.keyboard.press('Escape');assert(await tip.isHidden());
  assert(await term.evaluate(x=>x===document.activeElement),'Escape must retain focus');
  await page.keyboard.press('Enter');
  const detail=page.locator('#outbox-dialog');
  await detail.waitFor({state:'visible'});
  assert(await tip.isHidden(),'tooltip must not cover the detailed flow');
  assert.match(await detail.innerText(),/Kafka 발행 성공과 CORE 원장 반영 완료는 다르다/);
  assert.equal(await detail.locator('svg').count(),1);
  await page.screenshot({path:'/tmp/flow-outbox-desktop.png'});
  await page.keyboard.press('Escape');await detail.waitFor({state:'hidden'});
  assert(await term.evaluate(x=>x===document.activeElement),'closing detail must restore opener focus');
  await page.goto(url+'#sdk-event-delivery');
  await page.locator('#event-details-dialog').waitFor({state:'visible'});
  const modalTerm=page.locator('#sdk-event-delivery .term-tooltip[aria-controls="outbox-dialog"]').first();
  await modalTerm.hover();await tip.waitFor({state:'visible'});
  assert(await tip.evaluate(x=>x.closest('dialog')?.open),'tooltip must belong to the active modal');
  await page.keyboard.press('Escape');assert(await page.locator('#event-details-dialog').isVisible(),'Escape closed the modal');
  await page.screenshot({path:'/tmp/flow-tooltip-desktop.png'});
  const dlq=page.locator('#sdk-event-delivery .term-tooltip').filter({hasText:/^DLQ$/});
  await dlq.hover();await tip.waitFor({state:'visible'});
  assert.match(await tip.innerText(),/Dead Letter Queue/);
  assert.match(await tip.innerText(),/제공 여부는 확인이 필요/);
  await dlq.click();assert(await tip.isVisible());
  assert(await detail.isHidden(),'DLQ must not open the Outbox diagram');
  await page.keyboard.press('Escape');assert(await tip.isHidden());
  assert(await page.locator('#event-details-dialog').isVisible());
  await page.keyboard.press('Space');await tip.waitFor({state:'visible'});
  await page.keyboard.press('Escape');
  for(const word of ['Inbox','relay','멱등','원자적','2xx','4xx','5xx']){
   const entry=page.locator('#sdk-event-delivery .term-tooltip').filter({hasText:new RegExp('^'+word+'$')}).first();
   await entry.focus();await tip.waitFor({state:'visible'});
   assert((await tip.innerText()).length>20,word+' definition missing');
   assert(!await tip.innerText().then(x=>x.includes('<a ')),'tooltip must contain plain text');
   await page.keyboard.press('Escape');
  }
  await modalTerm.scrollIntoViewIfNeeded();
  const scrollBefore=await page.locator('#event-details-content').evaluate(x=>x.scrollTop);
  await modalTerm.focus();await page.keyboard.press('Space');
  await detail.waitFor({state:'visible'});
  await page.keyboard.press('Escape');await detail.waitFor({state:'hidden'});
  assert(await page.locator('#event-details-dialog').isVisible(),'nested close must preserve Queue details');
  assert.equal(await page.locator('#event-details-content').evaluate(x=>x.scrollTop),scrollBefore);
  assert(await modalTerm.evaluate(x=>x===document.activeElement));
  for(const width of [320,390]){
   await page.setViewportSize({width,height:844});
   await dlq.click();await tip.waitFor({state:'visible'});
   const dlqBox=await tip.boundingBox();assert(dlqBox.x>=8&&dlqBox.x+dlqBox.width<=width-8,'DLQ tooltip clipped');
   await page.screenshot({path:'/tmp/flow-dlq-'+width+'.png'});
   await page.keyboard.press('Escape');
   await modalTerm.hover();await tip.waitFor({state:'visible'});
   const b=await tip.boundingBox();assert(b.x>=8&&b.x+b.width<=width-8&&b.y>=8&&b.y+b.height<=844-8,'tooltip clipped');
   await page.screenshot({path:'/tmp/flow-tooltip-'+width+'.png'});
   await modalTerm.click();await detail.waitFor({state:'visible'});
   assert(await tip.isHidden());
   const d=await detail.boundingBox();assert(d.x>=0&&d.x+d.width<=width&&d.height<=844,'detail clipped');
   const content=page.locator('#outbox-content');
   assert(await content.evaluate(x=>x.scrollWidth<=x.clientWidth),'content must not overflow horizontally');
   const diagram=detail.locator('.outbox-diagram');
   await diagram.evaluate(x=>x.scrollLeft=x.scrollWidth);
   assert(await diagram.evaluate(x=>x.scrollLeft>0),'mobile diagram must scroll horizontally');
   await page.screenshot({path:'/tmp/flow-outbox-'+width+'.png'});
   await detail.locator('[data-outbox-close]').click();await detail.waitFor({state:'hidden'});
   assert(await page.locator('#event-details-dialog').isVisible());
  }
  await modalTerm.click();await detail.waitFor({state:'visible'});
  await page.mouse.click(1,1);await detail.waitFor({state:'hidden'});
  assert(await page.locator('#event-details-dialog').isVisible(),'backdrop closes only Outbox');
  await page.emulateMedia({media:'print'});
  assert(await page.locator('#bcm-outbox').isVisible(),'print must include the flow');
  const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});
  await nojs.goto(url);
  await nojs.locator('#contracts .term-tooltip').first().click();
  assert.equal(new URL(nojs.url()).hash,'#bcm-outbox');
  assert(await nojs.locator('#bcm-outbox').isVisible(),'no-JS flow must remain readable');
  assert.deepEqual(errors,[]);console.log('PASS: tooltip hover, Enter/Space, nested detail/focus/scroll, Escape/backdrop, 320/390px, print and no-JS');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
