CREATE TABLE bcm_acnt_crtn_l (
    acnt_id          VARCHAR(64)  PRIMARY KEY,
    acnt_typ_dvcd    VARCHAR(2)   NOT NULL,
    ref              VARCHAR(64)  NOT NULL,
    vndr_vlt_nm      VARCHAR(128) NOT NULL,
    idmp_key         VARCHAR(40)  NOT NULL UNIQUE,
    idmp_key_reg_dttm VARCHAR(16) NOT NULL,
    last_vndr_call_dttm VARCHAR(16),
    crtn_stcd        VARCHAR(16)  NOT NULL,
    try_cnt          INT          NOT NULL,
    vndr_vlt_id      VARCHAR(64),
    reg_dttm         VARCHAR(16)  NOT NULL,
    last_chng_dttm   VARCHAR(16)  NOT NULL,
    frst_reg_empno   VARCHAR(6)   NOT NULL,
    frst_reg_brcd    VARCHAR(4)   NOT NULL,
    last_chng_empno  VARCHAR(6)   NOT NULL,
    last_chng_brcd   VARCHAR(4)   NOT NULL,
    UNIQUE (acnt_typ_dvcd, ref),
    CHECK (crtn_stcd IN ('PENDING', 'SUBMITTING', 'COMPLETED')),
    CHECK (try_cnt >= 0),
    CHECK (last_vndr_call_dttm IS NULL OR last_vndr_call_dttm >= idmp_key_reg_dttm),
    CHECK ((crtn_stcd = 'COMPLETED') = (vndr_vlt_id IS NOT NULL))
);

CREATE TABLE bcm_addr_crtn_l (
    acnt_id          VARCHAR(64)  NOT NULL,
    ntwk_cd          VARCHAR(20)  NOT NULL,
    tkn_smbl         VARCHAR(16)  NOT NULL,
    vndr_ast_id      VARCHAR(64)  NOT NULL,
    idmp_key         VARCHAR(40)  NOT NULL UNIQUE,
    idmp_key_reg_dttm VARCHAR(16) NOT NULL,
    last_vndr_call_dttm VARCHAR(16),
    crtn_stcd        VARCHAR(16)  NOT NULL,
    try_cnt          INT          NOT NULL,
    dpst_addr        VARCHAR(128),
    reg_dttm         VARCHAR(16)  NOT NULL,
    last_chng_dttm   VARCHAR(16)  NOT NULL,
    frst_reg_empno   VARCHAR(6)   NOT NULL,
    frst_reg_brcd    VARCHAR(4)   NOT NULL,
    last_chng_empno  VARCHAR(6)   NOT NULL,
    last_chng_brcd   VARCHAR(4)   NOT NULL,
    PRIMARY KEY (acnt_id, ntwk_cd, tkn_smbl),
    FOREIGN KEY (acnt_id) REFERENCES bcm_acnt_m (acnt_id),
    CHECK (crtn_stcd IN ('PENDING', 'SUBMITTING', 'COMPLETED')),
    CHECK (try_cnt >= 0),
    CHECK (last_vndr_call_dttm IS NULL OR last_vndr_call_dttm >= idmp_key_reg_dttm),
    CHECK ((crtn_stcd = 'COMPLETED') = (dpst_addr IS NOT NULL))
);
