-- docs/design/03-bcm-db.md: V22 네트워크 지갑 원장. 기존 계정/주소 모델은 변경하지 않는다.
CREATE TABLE bcm_ntwk_wlt_crtn_l (
  crtn_id VARCHAR(64) PRIMARY KEY CHECK (crtn_id <> '' AND crtn_id !~ '^\s|\s$'),
  orgn_id VARCHAR(64) NOT NULL REFERENCES bcm_prvd_bndg_m(orgn_id),
  acnt_id VARCHAR(64) NOT NULL REFERENCES bcm_acnt_m(acnt_id),
  ntwk_cd VARCHAR(20) NOT NULL CHECK (ntwk_cd <> '' AND ntwk_cd !~ '^\s|\s$'),
  corr_id VARCHAR(64) NOT NULL CHECK (corr_id <> '' AND corr_id !~ '^\s|\s$'),
  req_hash VARCHAR(64) NOT NULL CHECK (req_hash ~ '^[0-9a-f]{64}$'),
  req_vrsn VARCHAR(32) NOT NULL CHECK (req_vrsn <> '' AND req_vrsn !~ '^\s|\s$'),
  vndr_ntwk VARCHAR(64) NOT NULL CHECK (vndr_ntwk <> '' AND vndr_ntwk !~ '^\s|\s$'),
  crtn_stcd VARCHAR(16) NOT NULL CHECK (crtn_stcd IN ('PREPARED', 'SUBMITTING', 'RECOVERING', 'COMPLETED', 'CONFLICT')),
  rvsn BIGINT NOT NULL CHECK (rvsn >= 0),
  post_prep_dttm VARCHAR(16) NULL CHECK (post_prep_dttm ~ '^[0-9]{14}$'),
  vndr_wlt_id VARCHAR(64) NULL CHECK (vndr_wlt_id <> '' AND vndr_wlt_id !~ '^\s|\s$'),
  scan_id VARCHAR(64) NULL CHECK (scan_id <> '' AND scan_id !~ '^\s|\s$'),
  next_crsr TEXT NULL CHECK (next_crsr <> '' AND next_crsr !~ '^\s|\s$'),
  scan_done_yn VARCHAR(1) NOT NULL CHECK (scan_done_yn IN ('Y', 'N')),
  last_rsn VARCHAR(64) NULL,
  reg_dttm VARCHAR(16) NOT NULL CHECK (reg_dttm ~ '^[0-9]{14}$'),
  last_chng_dttm VARCHAR(16) NOT NULL CHECK (last_chng_dttm ~ '^[0-9]{14}$'),
  frst_reg_empno VARCHAR(6) NOT NULL,
  frst_reg_brcd VARCHAR(4) NOT NULL,
  last_chng_empno VARCHAR(6) NOT NULL,
  last_chng_brcd VARCHAR(4) NOT NULL,
  UNIQUE (orgn_id, acnt_id, ntwk_cd),
  UNIQUE (orgn_id, corr_id),
  UNIQUE (crtn_id, orgn_id, acnt_id, ntwk_cd),
  CHECK ((crtn_stcd = 'PREPARED') = (post_prep_dttm IS NULL)),
  CHECK ((crtn_stcd IN ('PREPARED', 'SUBMITTING')) = (scan_id IS NULL)),
  CHECK (scan_done_yn = 'N' OR next_crsr IS NULL),
  CHECK (crtn_stcd <> 'COMPLETED' OR (vndr_wlt_id IS NOT NULL AND scan_done_yn = 'Y'))
);

CREATE TABLE bcm_ntwk_wlt_obs_l (
  page_id VARCHAR(64) PRIMARY KEY CHECK (page_id <> '' AND page_id !~ '^\s|\s$'),
  crtn_id VARCHAR(64) NOT NULL REFERENCES bcm_ntwk_wlt_crtn_l(crtn_id),
  scan_id VARCHAR(64) NOT NULL CHECK (scan_id <> '' AND scan_id !~ '^\s|\s$'),
  page_no INT NOT NULL CHECK (page_no >= 0),
  qry_crsr TEXT NULL CHECK (qry_crsr <> '' AND qry_crsr !~ '^\s|\s$'),
  next_crsr TEXT NULL CHECK (next_crsr <> '' AND next_crsr !~ '^\s|\s$'),
  evdc_ref VARCHAR(512) NOT NULL CHECK (evdc_ref <> '' AND evdc_ref !~ '^\s|\s$'),
  evdc_hash VARCHAR(64) NOT NULL CHECK (evdc_hash ~ '^[0-9a-f]{64}$'),
  obs_dttm VARCHAR(16) NOT NULL CHECK (obs_dttm ~ '^[0-9]{14}$'),
  frst_reg_empno VARCHAR(6) NOT NULL,
  frst_reg_brcd VARCHAR(4) NOT NULL,
  last_chng_empno VARCHAR(6) NOT NULL,
  last_chng_brcd VARCHAR(4) NOT NULL,
  UNIQUE (crtn_id, scan_id, page_no),
  UNIQUE (page_id, crtn_id)
);

CREATE TABLE bcm_ntwk_wlt_obs_item_l (
  page_id VARCHAR(64) NOT NULL,
  crtn_id VARCHAR(64) NOT NULL,
  item_no INT NOT NULL CHECK (item_no >= 0),
  orgn_id VARCHAR(64) NOT NULL CHECK (orgn_id <> '' AND orgn_id !~ '^\s|\s$'),
  exec_mode VARCHAR(16) NOT NULL,
  prtc_prvd VARCHAR(16) NOT NULL,
  pltfrm_inst_id VARCHAR(64) NOT NULL CHECK (pltfrm_inst_id <> '' AND pltfrm_inst_id !~ '^\s|\s$'),
  vndr_org_id VARCHAR(64) NOT NULL CHECK (vndr_org_id <> '' AND vndr_org_id !~ '^\s|\s$'),
  chain_mode VARCHAR(16) NOT NULL,
  ntwk_cd VARCHAR(20) NOT NULL CHECK (ntwk_cd <> '' AND ntwk_cd !~ '^\s|\s$'),
  vndr_wlt_id VARCHAR(64) NOT NULL CHECK (vndr_wlt_id <> '' AND vndr_wlt_id !~ '^\s|\s$'),
  corr_id VARCHAR(64) NULL CHECK (corr_id <> '' AND corr_id !~ '^\s|\s$'),
  ownr_dvcd VARCHAR(16) NOT NULL CHECK (ownr_dvcd IN ('ORGANIZATION', 'OTHER', 'UNVERIFIED')),
  wlt_addr VARCHAR(256) NULL CHECK (wlt_addr <> '' AND wlt_addr !~ '^\s|\s$'),
  frst_reg_empno VARCHAR(6) NOT NULL,
  frst_reg_brcd VARCHAR(4) NOT NULL,
  last_chng_empno VARCHAR(6) NOT NULL,
  last_chng_brcd VARCHAR(4) NOT NULL,
  PRIMARY KEY (page_id, item_no),
  FOREIGN KEY (page_id, crtn_id) REFERENCES bcm_ntwk_wlt_obs_l(page_id, crtn_id)
);

CREATE TABLE bcm_ntwk_wlt_m (
  crtn_id VARCHAR(64) PRIMARY KEY,
  orgn_id VARCHAR(64) NOT NULL,
  acnt_id VARCHAR(64) NOT NULL,
  ntwk_cd VARCHAR(20) NOT NULL,
  vndr_wlt_id VARCHAR(64) NOT NULL CHECK (vndr_wlt_id <> '' AND vndr_wlt_id !~ '^\s|\s$'),
  wlt_addr VARCHAR(256) NOT NULL CHECK (wlt_addr <> '' AND wlt_addr !~ '^\s|\s$'),
  page_id VARCHAR(64) NOT NULL,
  reg_dttm VARCHAR(16) NOT NULL CHECK (reg_dttm ~ '^[0-9]{14}$'),
  frst_reg_empno VARCHAR(6) NOT NULL,
  frst_reg_brcd VARCHAR(4) NOT NULL,
  last_chng_empno VARCHAR(6) NOT NULL,
  last_chng_brcd VARCHAR(4) NOT NULL,
  UNIQUE (orgn_id, acnt_id, ntwk_cd),
  UNIQUE (orgn_id, vndr_wlt_id),
  FOREIGN KEY (crtn_id, orgn_id, acnt_id, ntwk_cd) REFERENCES bcm_ntwk_wlt_crtn_l(crtn_id, orgn_id, acnt_id, ntwk_cd),
  FOREIGN KEY (page_id, crtn_id) REFERENCES bcm_ntwk_wlt_obs_l(page_id, crtn_id)
);
