// PLAYWRIGHT_MODULE may point to an existing Playwright installation.
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const cfg=JSON.parse(fs.readFileSync('/tmp/wallet-reference-test.json'));
const root=cfg.root,manifest=JSON.parse(fs.readFileSync(path.join(root,'readable-manifest.json')));
const out='/tmp/wallet-reference-verification';fs.mkdirSync(out,{recursive:true});
const report={archive:cfg.archive,root,checks:[],errors:[],external:[],pages:[]};
const url=p=>pathToFileURL(path.join(root,p)).href;
function assert(ok,msg){if(!ok)throw Error(msg)}
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});context.setDefaultTimeout(12000);
await context.route('**/*',r=>{if(/^https?:/.test(r.request().url())){report.external.push(r.request().url());return r.abort()}return r.continue()});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('requestfailed',r=>report.errors.push(r.url()+' '+r.failure().errorText));
async function guide(p){await page.goto(url(p));await page.waitForFunction(()=>document.documentElement.dataset.guideReady==='true')}
async function frame(){await page.waitForFunction(()=>document.querySelector('#reference-dialog').open&&document.querySelector('.reference-loading').hidden);return await(await page.locator('#reference-frame').elementHandle()).contentFrame()}
async function check(name,fn){try{await fn();report.checks.push({name,passed:true});console.log('PASS',name)}catch(e){report.checks.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message)}}
await check('The reported three reference links open new content without navigating the guide',async()=>{
 await guide('_guide/concepts.html');const links=page.locator('main .sources').first().locator('a');assert(await links.count()===3,'three references');
 for(let i=0;i<3;i++){const a=links.nth(i);await a.scrollIntoViewIfNeeded();const before=await page.evaluate(()=>({url:location.href,scroll:scrollY}));await a.click();const f=await frame();assert(f.url().includes('/_reference/'),'new reader');assert(page.url()===before.url,'guide URL changed');assert(await f.locator('article').innerText(),'missing content');assert(await f.locator('header').isHidden(),'old/full chrome in modal');await page.locator('[data-reference-close]').click();assert(await page.evaluate(()=>scrollY)===before.scroll,'reading position changed');assert(await a.evaluate(x=>x===document.activeElement),'opener focus')}
});
await check('Domain-model diagrams render in the modal',async()=>{await page.locator('main .sources').first().locator('a').nth(1).click();const f=await frame();await f.waitForFunction(()=>[...document.images].every(x=>x.complete&&x.naturalWidth>0));assert(await f.locator('.rendered-diagram img').count()===2,'two diagrams');await page.screenshot({path:path.join(out,'01-domain-modal.png')});await page.locator('[data-reference-close]').click()});
await check('Nested reference navigation stays in the modal and Back restores the document',async()=>{await page.locator('main .sources').first().locator('a').nth(1).click();let f=await frame();const original=f.url();const a=f.locator('article a[data-reference-title]:not([href*="accounts-wallets--domain-model.html"])').last();const nextPath=new URL(await a.getAttribute('href'),f.url()).pathname;await a.scrollIntoViewIfNeeded();const referenceScroll=await f.evaluate(()=>scrollY);await a.click();await page.waitForFunction(target=>new URL(document.querySelector('#reference-frame').src).pathname===target,nextPath);f=await frame();assert(f.url()!==original,'nested navigation');assert(f.url().includes('/_reference/'),'nested old target');await page.locator('[data-reference-back]').click();f=await frame();assert(f.url()===original,'back');await f.waitForFunction(top=>Math.abs(scrollY-top)<2,referenceScroll);await f.locator('article').click();await page.keyboard.press('Escape');await page.locator('#reference-dialog').waitFor({state:'hidden'});assert(await page.locator('#reference-dialog').isHidden(),'Escape from iframe')});
await check('New window opens the current rebuilt reference',async()=>{await guide('_guide/concepts.html');await page.locator('main .sources').first().locator('a').first().click();await frame();const [popup]=await Promise.all([context.waitForEvent('page'),page.locator('[data-reference-window]').click()]);await popup.waitForLoadState();assert(popup.url().includes('/_reference/accounts-wallets--accounts.html'),'popup URL');assert(!popup.url().includes('view=modal'),'popup embedded mode');assert(await popup.locator('header').isVisible(),'popup header');await popup.close();await page.locator('[data-reference-close]').click()});
await check('Search results open rebuilt API details in the same reader',async()=>{await guide('index.html');await page.locator('.search-open').click();await page.locator('#query').fill('/api/v1/sweeps');const match=page.locator('#results a[href*="reference--wallet--sweeps--sweeps-create.html"]');await match.waitFor();await match.click();const f=await frame();assert(page.url()===url('index.html'),'search left guide');assert(await f.locator('article').getByText('Idempotency-Key',{exact:true}).count()>0,'required header');await f.locator('summary').filter({hasText:/^Python$/}).click();assert(await f.locator('details[open]').filter({has: f.locator('summary').filter({hasText:/^Python$/})}).count()>0,'Python example');assert(await f.locator('blume-playground,form').count()===0,'old API runner');await page.screenshot({path:path.join(out,'02-api-modal.png')});await page.locator('[data-reference-close]').click();assert(await page.locator('.search-open').evaluate(x=>x===document.activeElement),'search focus restored')});
await check('Reference catalogue matches every current source page',async()=>{await guide('_guide/originals.html');const links=await page.locator('.original-list a').evaluateAll(xs=>xs.map(x=>({url:x.href,modal:x.hasAttribute('data-reference-title')})));assert(links.length===manifest.originalPages&&links.every(x=>x.modal&&x.url.includes('/_reference/')),'catalogue links')});
await check('Mobile full-screen modal and dismissal preserve the guide',async()=>{await page.setViewportSize({width:390,height:844});await guide('_guide/concepts.html');await page.locator('main .sources a').first().click();await frame();const b=await page.locator('#reference-dialog').boundingBox();assert(b.x===0&&b.y===0&&b.width===390&&b.height===844,'mobile fit');await page.screenshot({path:path.join(out,'03-mobile-modal.png')});await page.locator('[data-reference-close]').click();assert(page.url()===url('_guide/concepts.html'),'mobile guide URL')});
await check('Links open rebuilt references when JavaScript is disabled',async()=>{const offline=await browser.newContext({javaScriptEnabled:false});await offline.route('**/*',r=>{if(/^https?:/.test(r.request().url())){report.external.push(r.request().url());return r.abort()}return r.continue()});const source=await offline.newPage();await source.goto(url('_guide/concepts.html'));const [popup]=await Promise.all([offline.waitForEvent('page'),source.locator('main .sources a').first().click()]);await popup.waitForLoadState();assert(popup.url()===url('_reference/accounts-wallets--accounts.html'),'fallback new reader');assert(await popup.locator('article').isVisible(),'fallback body');assert(source.url()===url('_guide/concepts.html'),'fallback guide preserved');await offline.close()});
let next=0;
async function worker(){const p=await context.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>errors.push(r.url()+' '+r.failure().errorText));while(next<manifest.referencePages.length){const d=manifest.referencePages[next++];errors=[];try{await p.goto(url(d.path));await p.waitForFunction(()=>[...document.images].every(x=>x.complete&&x.naturalWidth>0));assert((await p.locator('article').innerText()).trim().length>0,'empty article');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page overflow');report.pages.push({path:d.path,passed:errors.length===0,errors:[...errors]})}catch(e){report.pages.push({path:d.path,passed:false,errors:[...errors,e.message]})}if(report.pages.length%50===0)console.log('PAGES',report.pages.length)}await p.close()}
await Promise.all([worker(),worker(),worker()]);
report.summary={checks:report.checks.length,failed:report.checks.filter(x=>!x.passed).length,pages:report.pages.length,pageFailures:report.pages.filter(x=>!x.passed).length,errors:report.errors.length,externalRequests:report.external.length};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('SUMMARY',JSON.stringify(report.summary));console.log('FAILED PAGES',JSON.stringify(report.pages.filter(x=>!x.passed)));await browser.close();if(report.summary.failed||report.summary.pageFailures||report.summary.errors||report.summary.externalRequests)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
